### PR TITLE
Format and clean code

### PR DESCRIPTION
**Pull request by thilinarmtb**

### CODE REVIEW

**Comment by nchristensen** [comment]
Is this from running autopep8?

**Comment by thilinarmtb** [comment]
```sh
black -l 80 *.py */*.py */*/*.py`
```
followed by
```sh
isort *.py */*.py */*/*.py
```

**Comment by thilinarmtb** [comment]
There are a lot of `flake8` failures. Probably need to be fixed before merging this.

**Comment by thilinarmtb** [comment]
What is with the `no_install` directory? Seems redundant.

**Comment by nchristensen** [comment]
Yeah we can probably resolve most of them by running autopep8 on all of the .py files like [here](https://stackoverflow.com/questions/72945417/run-autopep8-on-all-python-files-except-migrations-doable).

**Comment by nchristensen** [comment]
We should probably set up CI at some point too.

**Comment by thilinarmtb** [comment]
@nchristensen : Remaining flake8 errors are mainly related to `loopy` kernels. Can you clean it up?

**Review by nchristensen — APPROVED** [review]
lgtm

**Pull request merged**
